version: "3"
services:
  # mysql:
  #   image: mysql:5.7
  #   restart: always
  #   env_file:
  #     - .env
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_DATABASE=moviefy
  #   ports:
  #     - 127.0.0.1:3306:3306
  moviefy:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      # - node_modules:/app/node_modules
    # restart: always
    # env_file:
    #   - .env
    # depends_on:
    #   - mysql
# volumes:
#   node_modules:
#   mysql: