version: '3'
services:
  moviefy:
    image: moviefy-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "80:1010"
    command: npm start
volumes:
  node_modules: