version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DB
    ports:
      - "3306:3306"
    expose:
      - "3306"
  moviefy:
    depends_on:
      - mysql
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /app
    container_name: moviefy-app
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_HOST=MYSQL_REAL_HOST
      - MYSQL_LOCAL_PORT=3306
      - MYSQL_DATABASE=$MYSQL_DB
      - MYSQL_USERNAME=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    ports:
      - $PORT:$PORT
    # command: npm run dev